"""system_metrics migrate

Revision ID: 8fd620650223
Revises: 207c9b2ed14a
Create Date: 2025-02-25 21:56:43.979075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd620650223'
down_revision: Union[str, None] = '207c9b2ed14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('cpu_frequencies', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('cpu_times', sa.JSON(), nullable=True),
    sa.Column('cpu_stats', sa.JSON(), nullable=True),
    sa.Column('load_avg', sa.JSON(), nullable=True),
    sa.Column('memory_info', sa.JSON(), nullable=True),
    sa.Column('swap_memory', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_table('system_metrics')
    # ### end Alembic commands ###
